### ISSUE TITLE
FPC residual files

### ISSUE THREAD

**Issue by murnur19** [LongDirtyAnimAlf/Reiniero-fpcup#28]
First, thank you very much for continuing this project.

After compiling fpc I notice there is a lot of unused compiled units in in fpc subfolder.
Aren't they supposed to be moved to `fpc\units\*` ? or deleted. They are not used, so its considered garbage files.
```
fpc\compiler\*\units
fpc\utils\*\units
fpc\packages\*\units
fpc\rtl\units
```
They doubled the size of fpc folder.
Currently, I just delete them with batch script after running fpcup. I don't have any issue so far.

**Comment by LongDirtyAnimAlf** [comment]
Looks you're right !
I will have a look into it.

**Comment by murnur19** [comment]
Thanks.

**Comment by LongDirtyAnimAlf** [comment]
Thanks.

However, I need some extra feedback to be sure if changes are needed.
As far as I can see, the makefile of FPC itself does not move the compiled files, but just copies them when running "make install" !
If so, then:
* the residual files are there because of FPC itself, not because of fpcup.
* an extra option could be added for fpcup to get rid of these files.

My question (to be absolutely sure) : could you verify that FPC own "make install" copies files and not moves files ?

**Comment by LongDirtyAnimAlf** [comment]
Closed for no feedback.
