### ISSUE TITLE
Repository used to include prebuild binaries, where I can find them now?

### ISSUE THREAD

**Issue by mWaltari** [LongDirtyAnimAlf/Reiniero-fpcup#31]
Or at least I can't see them, and no mention that I could find them.

Or Do I need to delete local repository and clone it again... (I think that I did that already couple weeks ago)

**Comment by LongDirtyAnimAlf** [comment]
Is this what you mean:
https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/releases/tag/0.9-fpcup

**Comment by mWaltari** [comment]
Nope, I am pretty sure there was Truck-binaries and I did not have to fetch any of them separately.

Can't remember exactly how following started, but I am sure I did not compile the binaries myself at any point. And I am pretty sure I followed the Truck branch not any release branch.

**Comment by LongDirtyAnimAlf** [comment]
In that case I do not know what you mean.
The binaries were removed from the repository. To include binaries in a repo was wrong in the first place, and a mistake made by me.
So, the binaries are now available as a release. So, if you need the binaries, just download the appropriate one from the releases.
But I guess I understand you wrong, because the above is trivial, so please enlighten me if so.

**Comment by mWaltari** [comment]
No, that what I meant.

So I can't test with latest without compiling my self.

But your project, your rules.

Just have to use releases then

-tee-

**Comment by LongDirtyAnimAlf** [comment]
Ok. Now I understand !
Yes, you have to use the releases.
And yes, I have to update them for all the changes that are currently in trunk.
So, you are right. And I will update the releases !

**Comment by LongDirtyAnimAlf** [comment]
New (updated) release !
https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/releases/tag/1.1.0f
