### ISSUE TITLE
Trying to get working on small Debian console virtual machine

### ISSUE THREAD

**Issue by pbreneman** [LongDirtyAnimAlf/Reiniero-fpcup#4]
Help needed.  See wiki:  http://wiki.freepascal.org/Small_Virtual_Machines

**Comment by LongDirtyAnimAlf** [comment]
Is this the problem ?
"This application has failed to start because MSVCP60.dll was not found. Re-installing the application may fix this problem"

**Comment by pbreneman** [comment]
That is the problem on ReactOS but not on Debian.  Sadly I haven't been 
able to get either OS to work (for publishing in a simple way).

**Comment by LongDirtyAnimAlf** [comment]
About the ReactOS problem:
This is caused by the SVN client that fpcup downloads: it needs MSVCP60.dll !
You could instruct the user to download/install a SVN client before using fpcup.
E.g. from https://www.visualsvn.com/files/Apache-Subversion-1.9.0.zip'.
Please report back if this works for you.

Your problems on Linux are caused by a missing library.
Fpcup needs some library that is not installed in your distro.
I will look into this, because this is not expected behavior.
In the meantime, you can check the library dependencies of fpcup in your distro.
http://ask.xmodulo.com/check-library-dependency-program-process-linux.html

**Comment by pbreneman** [comment]
On 08/31/2015 02:35 AM, LongDirtyAnimAlf wrote:
> About the ReactOS problem:
> This is caused by the SVN client that fpcup downloads: it needs MSVCP60.dll !
> You could instruct the user to download/install a SVN client before using fpcup.
> E.g. from https://www.visualsvn.com/files/Apache-Subversion-1.9.0.zip'.
> Please report back if this works for you.
>
> Your problems on Linux are caused by a missing library.
> Fpcup needs some library that is not installed in your distro.
> I will look into this, because this is not expected behavior.
> In the meantime, you can check the library dependencies of fpcup in your distro.
> http://ask.xmodulo.com/check-library-dependency-program-process-linux.html

Thanks for the reply.

For ReactOS I'd rather use a SVN that you don't have to register to get, 
but I guess I should give up (for now) and use VisualSVN as you (and 
others at the ReactOS forum) have recommended.

A month ago I did some testing on Debian which you can read about here:
   http://lists.freepascal.org/pipermail/fpc-devel/2015-July/035870.html
Anything else I should try?
